<a href="https://colab.research.google.com/github/fularisankade45-arch/Fulari-FML-practicals/blob/main/TASK5_FULARI_ELECTRICAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ===========================================================
# Random Forest for Fault Detection in Wireless Communication
# ============================================================

# Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt

**Step 1: Load Dataset**

In [ ]:
import pandas as pd

data = pd.read_csv("/content/wireless_signal_quality_dataset.xlsx - Sheet1 (1).csv")

print("First Five Records")
data.head()

print("\nDataset Shape:")
print(data.shape)

First Five Records

Dataset Shape:
(100, 10)


**Step 2: Separate Features and Target**

In [ ]:
X = data.drop("Quality", axis=1)
y = data["Quality"]

**Step 3: Encode Target Labels**

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

print("\nClasses:")
print(encoder.classes_)


Classes:
['Excellent' 'Fair' 'Good' 'Poor']


**Step 4: Split Dataset**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
     X,
     y,
     test_size=0.25,
     random_state=42,
     stratify=y
     )

**Step 5: Build Random Forest Mode**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import DecisionTreeClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

**Step 6: Prediction**

In [ ]:
y_pred = rf.predict(X_test)

**Step 7: Accuracy**

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy = {:.2f}%".format(accuracy*100))


Accuracy = 88.00%


**Step 8: Classification Report**

In [ ]:
from sklearn.metrics import classification_report

print("\nClassification Report")

print(classification_report(
    y_test,
    y_pred,
    target_names=[str(c) for c in encoder.classes_]
    ))


Classification Report
              precision    recall  f1-score   support

   Excellent       0.00      0.00      0.00         1
        Fair       0.75      1.00      0.86         9
        Good       0.00      0.00      0.00         2
        Poor       1.00      1.00      1.00        13

    accuracy                           0.88        25
   macro avg       0.44      0.50      0.46        25
weighted avg       0.79      0.88      0.83        25



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


**Step 9: Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 0  1  0  0]
 [ 0  9  0  0]
 [ 0  2  0  0]
 [ 0  0  0 13]]


**Step10  :Feature Importance**

In [ ]:
importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
    )

importance = importance.sort_values(ascending=False)

print("\nFeature Importance")

print(importance)


Feature Importance
Signal_Strength_dBm          0.360444
SNR_dB                       0.207060
Estimated_Throughput_Mbps    0.150236
Interference_dB              0.079427
Distance_m                   0.060098
Noise_Floor_dBm              0.048804
Connected_Devices            0.047951
Channel_Bandwidth_MHz        0.028872
Frequency_GHz                0.017107
dtype: float64
